baseURL = "https://laszloszurok.github.io"
languageCode = "en-us"
title = "laszloszurok.github.io"
theme = "monospace-dark"
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[author]
    name = "László Szurok"

[params]
    messageTitle = "Welcome to my website!"
    messageContent = "I write about free and open source software and other IT related topics. You can find all posts under the POSTS menu."

[[menu.main]]
    name = "Arch-notes"
    url = "/arch-notes/"
    weight = 2
[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    
