baseURL = "https://pulzar.envs.net"
languageCode = "en-us"
title = "pulzar.envs.net"
theme = "hugo-theme"
copyright = '<a href="https://github.com/laszloszurok/blog-hugo/blob/master/LICENSE" target="_blank" rel="noopener">MIT</a>'

[params]
    messageTitle = "Welcome to my website!"
    messageContent = "I store some IT related (mostly linux desktop specific) notes here for personal use."
    customUrl = "https://github.com/laszloszurok"
[params.author]
    name = "László Szurok"

[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 1
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 2

[frontmatter]
enableGitInfo = true
lastmod = ["lastmod", ":fileModTime", ":default"]
